# Generated by Django 3.2.8 on 2021-11-03 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('objetivo', models.CharField(max_length=250)),
                ('informacionAlPublico', models.CharField(help_text='Informacion que se desea publicar', max_length=250)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fechas', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), blank=True, size=None)),
                ('cantidadMinimaAsistencia', models.IntegerField(blank=True, null=True)),
                ('cantidadHoras', models.IntegerField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=100, null=True)),
                ('apertura', models.DateTimeField(null=True)),
                ('cierre', models.DateTimeField(null=True)),
                ('observaciones', models.CharField(max_length=250)),
                ('area', models.ManyToManyField(help_text='Seleccione Area para esta Capacitacion', to='capacitacion.Area')),
            ],
        ),
    ]
