# Generated by Django 3.2.8 on 2021-10-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('objetivo', models.CharField(max_length=250)),
                ('informacionAlPublico', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
